name: Build Pake - EasyDoesIt

on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
        default: 'https://easydoesit.de'
      name:
        description: Name
        required: true
        default: 'EasyDoesIt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pake-cli
        run: npm install -g pake-cli@latest
      
      - name: Build
        run: |
          pake ${{ inputs.url }} --name ${{ inputs.name }}
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}-app
          path: ./output/
